### ISSUE TITLE
Handle missing sgf files 

### ISSUE THREAD

**Issue by glinares-em** [emerald-geomodelling/libnadagclient#5]
Extract information like **Maks boret lengde (m)** when the documentation (.zip) is missing.

**Comment by redhog** [comment]
We currently list all boreholes from the webpages [here](https://github.com/emerald-geomodelling/libnadagclient/blob/master/libnadagclient/__init__.py#L106) but then only use the ones that exists in any of the [project zip files](https://github.com/emerald-geomodelling/libnadagclient/blob/master/libnadagclient/__init__.py#L123). [After the loop](https://github.com/emerald-geomodelling/libnadagclient/blob/master/libnadagclient/__init__.py#L136) we need to go through all boreholes in the `borehole_map` that didn't end up being used to construct any of the `sections`, and build sections for them with something along these lines:
```
                    section = {"nadag": get_borehole_info(borehole_id)}

                    # Map some nadag attributes to the corresponding SGF ones
                    x, y = [float(c.split(":")[0]) for c in section["nadag"]["koord"].split(" ")]
                    z = float(section["nadag"]["hoeyde"].split(" ")[0])
                    section["main"][0]["x_coordinate"] = x
                    section["main"][0]["y_coordinate"] = y
                    section["main"][0]["z_coordinate"] = z
                    
                    res[borehole_id] = section
```

In addition, drill depth / depth to bedrock needs to be extracted from the `nadag` section and put in the `main` or `data` sections.
